### PR TITLE
Add three examples in /showcase

### PR DESCRIPTION
**Pull request by zemora**
This script shows the domain coloring of the klein's j- function

icosa

### CODE REVIEW

**Comment by rougier** [comment]
Thanks, but you could submit your example to the main matplotlib gallery in the showcase section, you would get more visibility.

**Comment by zemora** [comment]
I saw there are only codes, no images, so I'm not sure whether to put image files in that directory.

**Comment by rougier** [comment]
The image will be automatically generated when the documentation is build.

**Comment by zemora** [comment]
I added another two scripts. One is the smoothing color mandelbrot,  the other is a algorithm comes from algebraic combinatorics, which samples a random tiling of the 50 order aztec diamond graph with uniform probability (among all the 2^(1275) tilings).

**Comment by rougier** [comment]
Could you post (here) image as well ?

**Comment by zemora** [comment]
showcase-12

**Comment by zemora** [comment]
showcase-13

**Comment by zemora** [comment]
out

**Comment by zemora** [comment]
some other images with matplotlib:

breather_surface_matplotlib

**Comment by zemora** [comment]
The polynomial roots "fractal":

polyroots

**Comment by rougier** [comment]
Really nice.

**Comment by zemora** [comment]
OK, they are removed

**Comment by rougier** [comment]
I've it but it would be better to not have such dependency. A small message saying "Computing image..." would be enough

**Comment by zemora** [comment]
the `tqdm` dependency is also removed. in fact it took only one or two seconds to do the computation(as the order is not very large), most time are waiting for the matplotlib to output the image.

**Comment by zemora** [comment]
How about this image for a showcase?

polyroots

I was hesitate to add this one because it took 18 mins to generate such an image (maybe too long).

**Comment by rougier** [comment]
The point of the gallery is to show some specific matplotlib usage. I'm not sure this last one add anything new compare to the other you've submitted.

**Pull request merged**
